config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'dashboard', to: 'pages#dashboard'

  root 'products#index'

  resources :products, only: [:show, :index]

  put 'products/autocomplete', to: 'products#autocomplete'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id             :bigint(8)        not null, primary key
#  name           :string
#  description    :text
#  price_cents    :integer          default(0), not null
#  price_currency :string           default("USD"), not null
#  specifications :string           default([]), is an Array
#

class Product < ApplicationRecord
  searchkick word_start: [:name]

  monetize :price_cents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def show
    @product = Product.find(params[:id])
  end

  def index
    if params[:query].present?
      @products = Product.search(params[:query], page: params[:page])
    else
      @products = Product.all
    end
  end

  def autocomplete
    render json: Product.search(params[:query], {
      fields: ["name"],
      match: :word_start,
      limit: 10,
      load: false,
      misspellings: {below: 5}
    }).map(&:title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Verissa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.9.3/typeahead.min.js" %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.slim
h1 Index

= form_tag products_path, class: "form-inline", method: :get do
  = text_field_tag :query, params[:query], class: "form-control", name: "query"
  = submit_tag "Search", class: "btn btn-primary"
  - if params[:query].present?
    = link_to "clear", products_path

/ input#query name="query" type="text" /

/ = simple_form_for :product, url: products_search_path, method: :post do |form|
/   = form.input :search, label: 'Fecha de elaboracion: '
br
br
br

table
  thead
    tr
      th name
      th price
      th link
  tbody
    - @products.each do |product|
      tr
        td = product.name
        td = humanized_money_with_symbol product.price
        / td = product.category
        td = link_to('Detalle', product_path(product.id))


script src="jquery.js"
script src="typeahead.bundle.js"
javascript:
  | var products = new Bloodhound({
    | datumTokenizer: Bloodhound.tokenizers.whitespace,
    | queryTokenizer: Bloodhound.tokenizers.whitespace,
    | remote: {
      | url: '/products/autocomplete?query=%QUERY',
      | wildcard: '%QUERY'
    | }
  | });
  | $('#query').typeahead(null, {
    | source: products
  | });

app/views/products/show.html.slim
= link_to "Back", products_path

h1 = @product.name
p  = humanized_money_with_symbol @product.price
p  = @product.description
p  = @product.name

ui
  - @product.specifications.each do |spec|
    li = spec

br
input#discount name="discount" type="text" % de Descuento
button onclick="myFunction('#{@product.price}')" name="button" type="button" Calcular
p#nuevo_precio NUEVOPRECIO

javascript:
  function myFunction(precio) {
    var descuento = document.getElementById("discount").value;
    var nuevo_precio = precio - (precio*descuento/100)
    document.getElementById("nuevo_precio").innerHTML = `Precio con ${descuento}% de descuento: ` + nuevo_precio
    console.log(url)
  }